---
- name: Install Nginx on OracleLinux
  ansible.builtin.yum:
    name: nginx
    state: latest
  when: ansible_distribution == "OracleLinux"

- name: Update nginx conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '^listen [::]:80 default_server;'
    line: '# listen [::]:80 default_server;'
    state: present

- name: Copy Nginx configuration file
  copy:
    src: "{{conf_name}}"
    dest: /etc/nginx/conf.d/new.conf
    owner: root
    group: root
    mode: "0644"

- name: Create directory
  file:
    path: /var/www/{{webdirname}}
    state: directory

- name: Add index.html
  copy:
    src: "{{index_file}}"
    dest: /var/www/{{webdirname}}/index.html
    owner: root
    group: root
    mode: "0644"

- name: Restart Nginx service
  service:
    name: nginx
    state: restarted

