---
- name: Install Nginx for Debian
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Nginx for OracleLinux
  import_tasks: oracle.yml
  when: ansible_distribution == "OracleLinux"

- name: Copy Nginx configuration file
  copy:
    src: "{{conf_name}}"
    dest: /etc/nginx/conf.d/new.conf
    owner: root
    group: root
    mode: "0644"

- name: Create directory
  file:
    path: /var/www/{{webdirname}}
    state: directory

- name: Add index.html
  copy:
    src: "{{index_file}}"
    dest: /var/www/{{webdirname}}/index.html
    owner: root
    group: root
    mode: "0644"

- name: Restart Nginx service
  shell:
    cmd: systemctl restart nginx

