---
- name: Install Nginx on OracleLinux
  ansible.builtin.yum:
    name: nginx
    state: latest
  when: ansible_distribution == "OracleLinux"

- name: Update nginx conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '^listen [::]:80 default_server;'
    line: '# listen [::]:80 default_server;'
    state: present
