---
- name: Add the user to the sudo group
  hosts: "{{variable_hosts | default('practise')}}"
  vars:
    username: "newuser"
  tasks:
    - ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        append: yes

