---
- name: Add the user to the sudo group
  vars:
    username: "newuser"
  ansible.builtin.user:
    name: "{{ username }}"
    groups: sudo
    append: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel
    append: yes
  when: ansible_distribution == 'OracleLinux'

