---
- name: Create new user 
  vars:
    my_password: "QazWsx321"
    username: "newuser"
  ansible.builtin.user:
    name: "{{username}}"
    password: "{{my_password}}"
    state: present
    create_home: yes
    home: "/home/{{username}}"
    shell: /bin/bash
    
