---
- name: Create new user 
  ansible.builtin.user:
    name: "{{username}}"
    password: "{{my_password | string | password_hash('sha512')}}"
    update_password: always
    state: present
    create_home: yes
    home: "/home/{{username}}"
    shell: /bin/bash
    
