---
- name: Update SSH Port in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: 'Port {{newport}}'
    backup: yes

- name: Restart SSH
  ansible.builtin.service:
    name: sshd
    state: restarted
